/* tslint:disable */
/* eslint-disable */
/**
 * Autonomous Hive REST API
 * OpenAPI documentation for all Autonomous Hive API endpoints.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@wujibear.studio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ColonyMeta } from './ColonyMeta';
import {
    ColonyMetaFromJSON,
    ColonyMetaFromJSONTyped,
    ColonyMetaToJSON,
} from './ColonyMeta';

/**
 * Tags for industry (automotive, legal services, clothing, software, etc.), could also be inferred from products
 * @export
 * @interface Colony
 */
export interface Colony {
    /**
     * 
     * @type {any}
     * @memberof Colony
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Colony
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Colony
     */
    logo?: any;
    /**
     * 
     * @type {any}
     * @memberof Colony
     */
    parentColonyId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Colony
     */
    userIds?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Colony
     */
    primaryIndustry?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Colony
     */
    structureType?: ColonyStructureTypeEnum;
    /**
     * 
     * @type {ColonyMeta}
     * @memberof Colony
     */
    meta?: ColonyMeta;
}


/**
 * @export
 */
export const ColonyStructureTypeEnum = {
    Coop: 'coop',
    NonProfit: 'non profit',
    Ceo: 'ceo',
    Shareholders: 'shareholders'
} as const;
export type ColonyStructureTypeEnum = typeof ColonyStructureTypeEnum[keyof typeof ColonyStructureTypeEnum];


/**
 * Check if a given object implements the Colony interface.
 */
export function instanceOfColony(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ColonyFromJSON(json: any): Colony {
    return ColonyFromJSONTyped(json, false);
}

export function ColonyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Colony {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'logo': !exists(json, 'logo') ? undefined : json['logo'],
        'parentColonyId': !exists(json, 'parentColonyId') ? undefined : json['parentColonyId'],
        'userIds': !exists(json, 'userIds') ? undefined : json['userIds'],
        'primaryIndustry': !exists(json, 'primaryIndustry') ? undefined : json['primaryIndustry'],
        'structureType': !exists(json, 'structureType') ? undefined : json['structureType'],
        'meta': !exists(json, 'meta') ? undefined : ColonyMetaFromJSON(json['meta']),
    };
}

export function ColonyToJSON(value?: Colony | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'logo': value.logo,
        'parentColonyId': value.parentColonyId,
        'userIds': value.userIds,
        'primaryIndustry': value.primaryIndustry,
        'structureType': value.structureType,
        'meta': ColonyMetaToJSON(value.meta),
    };
}

