/* tslint:disable */
/* eslint-disable */
/**
 * Autonomous Hive REST API
 * OpenAPI documentation for all Autonomous Hive API endpoints.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@wujibear.studio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Colony } from './Colony';
import {
    ColonyFromJSON,
    ColonyFromJSONTyped,
    ColonyToJSON,
} from './Colony';

/**
 * 
 * @export
 * @interface GetColonies200Response
 */
export interface GetColonies200Response {
    /**
     * 
     * @type {Colony}
     * @memberof GetColonies200Response
     */
    colonies?: Colony;
}

/**
 * Check if a given object implements the GetColonies200Response interface.
 */
export function instanceOfGetColonies200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetColonies200ResponseFromJSON(json: any): GetColonies200Response {
    return GetColonies200ResponseFromJSONTyped(json, false);
}

export function GetColonies200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetColonies200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'colonies': !exists(json, 'colonies') ? undefined : ColonyFromJSON(json['colonies']),
    };
}

export function GetColonies200ResponseToJSON(value?: GetColonies200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'colonies': ColonyToJSON(value.colonies),
    };
}

