/* tslint:disable */
/* eslint-disable */
/**
 * Autonomous Hive REST API
 * OpenAPI documentation for all Autonomous Hive API endpoints.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@wujibear.studio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
} from './PaginationMeta';

/**
 * 
 * @export
 * @interface GetCells200Response
 */
export interface GetCells200Response {
    /**
     * 
     * @type {any}
     * @memberof GetCells200Response
     */
    cells?: any | null;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof GetCells200Response
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the GetCells200Response interface.
 */
export function instanceOfGetCells200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetCells200ResponseFromJSON(json: any): GetCells200Response {
    return GetCells200ResponseFromJSONTyped(json, false);
}

export function GetCells200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCells200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cells': !exists(json, 'cells') ? undefined : json['cells'],
        'meta': !exists(json, 'meta') ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function GetCells200ResponseToJSON(value?: GetCells200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cells': value.cells,
        'meta': PaginationMetaToJSON(value.meta),
    };
}

