/* tslint:disable */
/* eslint-disable */
/**
 * Autonomous Hive REST API
 * OpenAPI documentation for all Autonomous Hive API endpoints.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSession404Response
 */
export interface GetSession404Response {
    /**
     * 
     * @type {any}
     * @memberof GetSession404Response
     */
    errors?: any | null;
}

/**
 * Check if a given object implements the GetSession404Response interface.
 */
export function instanceOfGetSession404Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetSession404ResponseFromJSON(json: any): GetSession404Response {
    return GetSession404ResponseFromJSONTyped(json, false);
}

export function GetSession404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSession404Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function GetSession404ResponseToJSON(value?: GetSession404Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': value.errors,
    };
}

