/* tslint:disable */
/* eslint-disable */
/**
 * Autonomous Hive REST API
 * OpenAPI documentation for all Autonomous Hive API endpoints.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@wujibear.studio
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {any}
     * @memberof ModelError
     */
    errorCode: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModelError
     */
    message: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModelError
     */
    identifier?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModelError
     */
    attribute?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModelError
     */
    object?: any | null;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "errorCode" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'],
        'message': json['message'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'attribute': !exists(json, 'attribute') ? undefined : json['attribute'],
        'object': !exists(json, 'object') ? undefined : json['object'],
    };
}

export function ModelErrorToJSON(value?: ModelError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorCode': value.errorCode,
        'message': value.message,
        'identifier': value.identifier,
        'attribute': value.attribute,
        'object': value.object,
    };
}

